[package]
name = "tarkka"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "lookup"
path = "src/lookup.rs"

[lib]
crate-type = ["cdylib", "rlib"]
name = "tarkka"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
zeekstd = "0.6.0"
tarkka_derive = { path = "tarkka_derive" }

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.21.1", default-features = false }
