[package]
name = "tarkka"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test_decompress"
path = "src/test_decompress.rs"

[[bin]]
name = "lookup"
path = "src/lookup.rs"


[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
zeekstd = "0.6.0"
